"""add device peer_serial_number

Revision ID: c48a83a1ea78
Revises: df8b51f16228
Create Date: 2026-08-10 09:58:50.707037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c48a83a1ea78'
down_revision: Union[str, Sequence[str], None] = 'df8b51f16228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_alerts_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('sequence', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_audit_events_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_events_hash')),
    sa.UniqueConstraint('sequence', name=op.f('uq_audit_events_sequence'))
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('passes',
    sa.Column('satellite_device_id', sa.UUID(), nullable=False),
    sa.Column('ground_device_id', sa.UUID(), nullable=False),
    sa.Column('aos', sa.DateTime(timezone=True), nullable=False),
    sa.Column('los', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_elevation_deg', sa.Float(), nullable=True),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ground_device_id'], ['devices.id'], name=op.f('fk_passes_ground_device_id_devices')),
    sa.ForeignKeyConstraint(['satellite_device_id'], ['devices.id'], name=op.f('fk_passes_satellite_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passes'))
    )
    op.create_index(op.f('ix_passes_created_at'), 'passes', ['created_at'], unique=False)
    op.create_table('telemetry_records',
    sa.Column('source_device_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.String(length=32), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], name=op.f('fk_telemetry_records_source_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_records'))
    )
    op.create_index(op.f('ix_telemetry_records_recorded_at'), 'telemetry_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_telemetry_records_source_device_id'), 'telemetry_records', ['source_device_id'], unique=False)
    op.add_column('devices', sa.Column('peer_serial_number', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'peer_serial_number')
    op.drop_index(op.f('ix_telemetry_records_source_device_id'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_recorded_at'), table_name='telemetry_records')
    op.drop_table('telemetry_records')
    op.drop_index(op.f('ix_passes_created_at'), table_name='passes')
    op.drop_table('passes')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
