"""add device, key, job tables

Revision ID: df8b51f16228
Revises: 
Create Date: 2026-08-07 08:17:01.720414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df8b51f16228'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('ORIGO_SPACE', 'ORIGO_TERRESTRIAL', name='devicetype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PROVISIONED', 'ACTIVE', 'DECOMMISSIONED', name='devicestatus', native_enum=False, length=32), nullable=False),
    sa.Column('mission', sa.String(length=128), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_created_at'), 'devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_index(op.f('ix_devices_type'), 'devices', ['type'], unique=False)
    op.create_table('keys',
    sa.Column('satellite_device_id', sa.UUID(), nullable=False),
    sa.Column('ground_device_id', sa.UUID(), nullable=False),
    sa.Column('kem_param_set', sa.Enum('ML_KEM_512', 'ML_KEM_768', 'ML_KEM_1024', name='kemparamset', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('PENDING_KEYGEN', 'EK_SENT', 'AWAITING_CT', 'DECAPS_COMPLETE', 'ACTIVE', 'SUPERSEDED', 'REVOKED', 'DESTROYED', name='keystate', native_enum=False, length=32), nullable=False),
    sa.Column('hsm_key_reference', sa.String(length=128), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_key_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ground_device_id'], ['devices.id'], name=op.f('fk_keys_ground_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['satellite_device_id'], ['devices.id'], name=op.f('fk_keys_satellite_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_key_id'], ['keys.id'], name=op.f('fk_keys_superseded_by_key_id_keys'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keys'))
    )
    op.create_index(op.f('ix_keys_created_at'), 'keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_keys_state'), 'keys', ['state'], unique=False)
    op.create_index('uq_keys_one_active_per_pair', 'keys', ['satellite_device_id', 'ground_device_id'], unique=True, postgresql_where=sa.text("state = 'ACTIVE'"))
    op.create_table('jobs',
    sa.Column('type', sa.Enum('KEY_EXCHANGE', 'DATA_DELIVERY', 'CONFIG_PUSH', 'SELF_TEST', name='jobtype', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('SCHEDULED', 'DISPATCHED', 'EK_SENT', 'CT_RECEIVED', 'ACTIVE', 'FAILED', 'TIMED_OUT', name='jobstate', native_enum=False, length=32), nullable=False),
    sa.Column('satellite_device_id', sa.UUID(), nullable=False),
    sa.Column('ground_device_id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.UUID(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ground_device_id'], ['devices.id'], name=op.f('fk_jobs_ground_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['key_id'], ['keys.id'], name=op.f('fk_jobs_key_id_keys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['satellite_device_id'], ['devices.id'], name=op.f('fk_jobs_satellite_device_id_devices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_ground_device_id'), 'jobs', ['ground_device_id'], unique=False)
    op.create_index(op.f('ix_jobs_satellite_device_id'), 'jobs', ['satellite_device_id'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_satellite_device_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_ground_device_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('uq_keys_one_active_per_pair', table_name='keys', postgresql_where=sa.text("state = 'ACTIVE'"))
    op.drop_index(op.f('ix_keys_state'), table_name='keys')
    op.drop_index(op.f('ix_keys_created_at'), table_name='keys')
    op.drop_table('keys')
    op.drop_index(op.f('ix_devices_type'), table_name='devices')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_created_at'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
