"""add provisioning status to devices

Revision ID: f6cf6cd0838f
Revises: c48a83a1ea78
Create Date: 2026-08-11 05:04:59.847115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6cf6cd0838f'
down_revision: Union[str, Sequence[str], None] = 'c48a83a1ea78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('provisioning_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'provisioning_status')
    # ### end Alembic commands ###
